

title: Dark Star
email: later
description: >-
  موقع دارك الجديد المبني بالكامل من الصفر
baseurl: /site
url: darkst13.github.io 
github_username: darkst13


plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: _sass


exclude:
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - note.note
